### PR TITLE
top bar implemented on search branch, but deploying immediately

### PR DESCRIPTION
**Pull request by jangsus1**
바로 가져다 쓰시면 됩니다 :)

### CODE REVIEW

**Comment by Kojihyung** [comment]
LGTM☆

**Comment by kdh9949** [comment]
LGTM :) :1st_place_medal: :1st_place_medal: :1st_place_medal:

**Comment by geeglegeegle45** [comment]
good!

**Comment by kdh9949** [comment]
LGTM :100: :100: :100: :100: :100:

**Comment by Kojihyung** [comment]
💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯

**Comment by geeglegeegle45** [comment]
👍 👍 👍 good

**Pull request merged**
